sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Dpcms1YFBXbCb4sRBIIx7Drm8KuOeNoGYCRwrXNZKjtnNzHKihoutGvFKIzknkahnQ+1AHvsdCTIiIVaXO1FaMWVaF7QgVTbYsYAgV44xVbaO6DfeZeyVDpYQfrm60VL5aL21xKFDEX3F+ypBIvQETHmmFvgA+lGWZF82h8B5U75hD+ydllK+kS6wy6VYAh2Y+E/heR1VjhdgrNxi5Zfe0vG11k0iYCz7b/OR3iuY6vBOXyi+YQvQVepT75Y8pbIVt7hWuOgjGZLtUi+ugKDYXkB/ymDwuHWWli/5E+uVPMa1vAIajQqtk44nlHs4O7pw+DGxLtF9A2hZsFZJELnGjAPAFDg3qaTDQBRvHh26HX1T6J6CXet6gB1X9o4nO4jzCkeAgn03HSES36IexCU3zG/fSxV5yqcUnfAkbYdSjmy9ts1u8HcYqaTSsJ/AWw+vGHXzXNv/dOAJ1gEhcELbCPymbb58L1GYHuTQBicWbLjI2jy3vQoyd1VkrnlHbHWNkmS8e2ct8mo1pCIomTQpULoEbFN6WrKUdR11DT5foHgBxFDavz/CmKWrT/jN84wOrN2CKimGkep8Z8Q6XO2nheeK3Tl/byjguPn6KljzJBOAhv/3Bll4PkSX6AyY4iWuC5hqlW5BY8rN9sZu2HPeHDwo8aLS7RUTdtYD7LX6xQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Myths-and-Myth-Makers--13-Old-Tales-and-Superstitions-Interpreted-by-Comparative-Mythology_1061
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy